### ISSUE TITLE
Errors for post requests

### ISSUE THREAD

**Issue by nahim-alhyane** [exceptionnotfound/AspNetCoreRequestResponseMiddlewareDemo#1]
Hello,

I checked your code and i ran into an error during "post" messages.
The request body was empty resulting in the following error:
A non-empty request body is required.

I changed the code in the FormatRequest method:
* copy of the request body is not necessary (enabled by enableRewind())
* reset the stream to the start: request.Body.Seek(0, SeekOrigin.Begin);
=> then it worked like a charm :-)

Just wanted to let you know.

Regards,

Nahim Alhyane
Belgium

Code:

 //This line allows us to set the reader for the request back at the beginning of its stream.
            request.EnableRewind();

            //We now need to read the request stream.  First, we create a new byte[] with the same length as the request stream...
            var buffer = new byte[Convert.ToInt32(request.ContentLength)];

            //...Then we copy the entire request stream into the new buffer.
            await request.Body.ReadAsync(buffer, 0, buffer.Length);

            //We convert the byte[] into a string using UTF8 encoding...
            var bodyAsText = Encoding.UTF8.GetString(buffer);

            // Reset the stream to start:
            request.Body.Seek(0, SeekOrigin.Begin);
            
            return $"{request.Scheme} {request.Host}{request.Path} {request.QueryString} {bodyAsText}";

**Comment by nmg196** [comment]
The function request.EnableRewind() doesn't seem to exist in .NET core 3, so I think it needs to be changed to request.EnableBuffering()

**Comment by progmars** [comment]
I too had the same issue and came to the same solution of                 
```
request.Body.Seek(0, SeekOrigin.Begin);
```

Not sure why request Body assignment was there at all - it's just a ref pointer to the stream, you are not changing or resetting anything by assigning the same ref back.

**Comment by exceptionnotfound** [comment]
Thanks for pointing this out! The project has been upgraded to ASP.NET Core 3.1.
