### ISSUE TITLE
Code does not work for .Net Core 3.1

### ISSUE THREAD

**Issue by LeslieMurphy** [exceptionnotfound/AspNetCoreRequestResponseMiddlewareDemo#2]
I had to change:

`request.EnableRewind(); 
`
to 
`HttpRequestRewindExtensions.EnableBuffering(request);`

**Comment by exceptionnotfound** [comment]
I am not finding the line `request.EnableRewind()`. I am, however, finding the line `request.EnableBuffering()`, and it does seem to work on .NET Core 3.1 for me. Could this be the problem?

**Comment by LeslieMurphy** [comment]
Aha - I see my issue!   Your blog post at https://exceptionnotfound.net/using-middleware-to-log-requests-and-responses-in-asp-net-core/  (excellent by the way) still has the .Net Core 2.0 code.  I see the updated code in your repo.  If you have a chance, update the web page too!  

Since `HttpRequestRewindExtensions.EnableBuffering(request);` is the extension method, your code is simpler :-)

`request.EnableBuffering()` is the way to go!
